Blog.Web/Areas/Admin/Controllers/HomeController.cs
using Blog.Entity.Entities;
using Blog.Service.Services.Abstractions;
using Blog.Service.Services.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Blog.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class HomeController : Controller
    {
        private readonly IArticleService articleService;
        private readonly IDashboradService dashboradService;

        public HomeController(IArticleService articleService, IDashboradService dashboradService)
        {
            this.articleService = articleService;
            this.dashboradService = dashboradService;
        }
        public async Task<IActionResult> Index()
        {
            var articles = await articleService.GetAllArticlesWithCategoryNonDeletedAsync();

            return View(articles);
        }
        [HttpGet]
        public async Task<IActionResult> YearlyArticleCounts()
        {
            var count = await dashboradService.GetYearlyCounts();
            return Json(JsonConvert.SerializeObject(count));
        }
        [HttpGet]
        public async Task<IActionResult> TotalArticleCount()
        {
            var count = await dashboradService.GetTotalArticleCount();
            return Json(count);
        }
        [HttpGet]
        public async Task<IActionResult> TotalCategoryCount()
        {
            var count = await dashboradService.GetTotalCategoryCount();
            return Json(count);
        }
    }
}

Blog.Web/Controllers/HomeController.cs
using Blog.Data.UnitOfWorks;
using Blog.Entity.Entities;
using Blog.Service.Services.Abstractions;
using Blog.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Blog.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IArticleService articleService;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly IUnitOfWork unitOfWork;

        public HomeController(ILogger<HomeController> logger,IArticleService articleService , IHttpContextAccessor httpContextAccessor, IUnitOfWork unitOfWork)
        {
            _logger = logger;
            this.articleService= articleService;
            this.httpContextAccessor = httpContextAccessor;
            this.unitOfWork = unitOfWork;
        }

        [HttpGet]
        public  async Task<IActionResult> Index(Guid? categoryId, int currentPage = 1, int pageSize = 3, bool isAscending = false)
        {
            var articles = await articleService.GetAllByPagingAsync(categoryId, currentPage, pageSize, isAscending);
            return View(articles);
        }

        [HttpGet]
        public async Task<IActionResult> Search(string keyword, int currentPage = 1, int pageSize = 3, bool isAscending = false)
        {
            var articles = await articleService.SearchAsync(keyword, currentPage, pageSize, isAscending);
            return View(articles);
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public async Task<IActionResult> Detail(Guid id)
        {
            var ipAddress = httpContextAccessor.HttpContext.Connection.RemoteIpAddress.MapToIPv4().ToString();
            var articeVisitors = await unitOfWork.GetRepository<ArticleVisitor>().GetAllAsync(null, x => x.Visitor, y => y.Article);
            var article = await unitOfWork.GetRepository<Article>().GetAsync(x => x.Id == id);

            var result = await articleService.GetArticlesWithCategoryNonDeletedAsync(id);

            var visitor = await unitOfWork.GetRepository<Visitor>().GetAsync(x => x.IpAddress == ipAddress);

            var addArticleVisitors = new ArticleVisitor(article.Id, visitor.Id);

            if (articeVisitors.Any(x => x.VisitorId == addArticleVisitors.VisitorId && x.ArticleId == addArticleVisitors.ArticleId))
                return View(result);
            else
            {
                await unitOfWork.GetRepository<ArticleVisitor>().AddAsync(addArticleVisitors);
                article.ViewCount += 1;
                await unitOfWork.GetRepository<Article>().UpdateAsync(article);
                await unitOfWork.SaveAsync();
            }

            return View(result);
        }
    }
}

Blog.Web/ViewComponents/HomeCategoriesViewComponent.cs
using Blog.Service.Services.Abstractions;
using Microsoft.AspNetCore.Mvc;

namespace YoutubeBlog.Web.ViewComponents
{
    public class HomeCategoriesViewComponent : ViewComponent
    {
        private readonly ICategoryService categoryService;

        public HomeCategoriesViewComponent(ICategoryService categoryService)
        {
            this.categoryService = categoryService;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await categoryService.GetAllCategoriesNonDeletedTake24();
            return View(categories);
        }
    }
}

Blog.Web/Views/Home/Detail.cshtml
@model ArticleDto


<section class="blog-posts">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="all-blog-posts">
                    <div class="row">
                        <div class="col-lg-12">

                            <div class="blog-post">
                                <div class="blog-thumb">
                                    <img src="~/stand-blog/assets/images/blog-post-01.jpg" alt="">
                                </div>
                                <div class="down-content">
                                    <a href="#"><h4>@Model.Title</h4></a>
                                    <ul class="post-info">
                                        <li>@Model.User.FirstName @Model.User.LastName</li>
                                        <li>@Model.CreatedDate.ToString("dd/MM/yyyy")</li>
                                        <li><i class="fa-solid fa-eye"></i> @Model.ViewCount</li>
                                    </ul>
                                    <p>
                                        @Model.Content
                                    </p>
                                    <div class="post-options">
                                        <div class="row">
                                            <div class="col-6">
                                                <ul class="post-tags">
                                                    <li><i class="fa fa-tags"></i></li>
                                                    <li><a href="#">@Model.Category.Name</a></li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Blog.Web/Views/Home/Index.cshtml
@model ArticleListDto

<section class="blog-posts">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                        <div class="col-lg-12">
                            @foreach (var item in Model.Articles)
                            {
                                <input type="hidden" id="keyword" value="@Model.CurrentPage"/>
                                <div class="blog-post">
                                    <div class="blog-thumb">
                                        <img src=@item.Image.FileName alt="">
                                    </div>
                                    <div class="down-content">
                                        <a asp-controller="Home" asp-action="Detail" asp-route-id="@item.Id"><h4>@item.Title</h4></a>
                                        <ul class="post-info">
                                            <li>@item.User.FirstName @item.User.LastName</li>
                                            <li>@item.CreatedDate.ToString("dd/MM/yyyy")</li>
                                            <li><i class="fa-solid fa-eye"></i> @item.ViewCount</li>
                                        </ul>
                                        <p>
                                            @(item.Content.Length > 280 ? item.Content.Substring(0, 280) : item.Content) ...
                                        </p>
                                        <div class="post-options">
                                            <div class="row">
                                                <div class="col-6">
                                                    <ul class="post-tags">
                                                        <li><i class="fa fa-tags"></i></li>
                                                        <li><a href="#">@item.Category.Name</a></li>
                                                    </ul>
                                                </div>
                                                <div class="col-6">
                                                    <ul class="post-share">
                                                        <li><i class="fa fa-link"></i></li>
                                                        <li><a asp-controller="Home" asp-action="Detail" asp-route-id="@item.Id">[Devamını Oku]</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                        <div class="col-lg-12">
                            @*<div class="main-button">
                            <a href="blog.html">View All Posts</a>
                            </div>*@

                            <ul class="pagination justify-content-center mb-4 mt-4 btn-block">

                                @if (Model.ShowPrevious)
                                {
                                    <li class="page-item">
                                        <a class="page-link" asp-route-currentPage="@(Model.CurrentPage - 1)" asp-route-pageSize="@Model.PageSize"> Önceki </a>
                                    </li>
                                }
                                @for (int i = 1; i < Model.TotalPages; i++)
                                {
                                    <li class="page-item @(i == Model.CurrentPage ? "active" : "")">

                                        <a class="page-link" asp-route-currentPage="@i" asp-route-pageSize="@Model.PageSize"> @i </a>
                                    </li>
                                }
                                @if (Model.ShowNext)
                                {
                                    <li class="page-item">
                                        <a class="page-link" asp-route-currentPage="@(Model.CurrentPage + 1)" asp-route-pageSize="@Model.PageSize"> Sonraki </a>
                                    </li>
                                }

                            </ul>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="sidebar">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="sidebar-item search">
                                <form id="search_form" asp-controller="Home" asp-action="Search" method="GET">
                                    <input type="text" name="keyword" class="searchText" placeholder="Arama yapınız..." autocomplete="on">
                                </form>
                            </div>
                        </div>
                        @*<div class="col-lg-12">
                            <div class="sidebar-item recent-posts">
                                <div class="sidebar-heading">
                                    <h2>Recent Posts</h2>
                                </div>
                                <div class="content">
                                    <ul>
                                        <li>
                                            <a href="post-details.html">
                                                <h5>Vestibulum id turpis porttitor sapien facilisis scelerisque</h5>
                                                <span>May 31, 2020</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="post-details.html">
                                                <h5>Suspendisse et metus nec libero ultrices varius eget in risus</h5>
                                                <span>May 28, 2020</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="post-details.html">
                                                <h5>Swag hella echo park leggings, shaman cornhole ethical coloring</h5>
                                                <span>May 14, 2020</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>*@
                        <div class="col-lg-12">
                            <div class="sidebar-item categories">
                                <div class="sidebar-heading">
                                    <h2>KATEGORİLER</h2>
                                </div>
                                @await Component.InvokeAsync("HomeCategories")
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

Blog.Web/Views/Home/Search.cshtml
@model ArticleListDto

<section class="blog-posts">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                        <div class="col-lg-12">
                            @foreach (var item in Model.Articles)
                            {

                                <div class="blog-post">
                                    <div class="blog-thumb">
                                        <img src="~/stand-blog/assets/images/blog-post-01.jpg" alt="">
                                    </div>
                                    <div class="down-content">
                                        <a href="post-details.html"><h4>@item.Title</h4></a>
                                        <ul class="post-info">
                                            <li>@item.User.FirstName @item.User.LastName</li>
                                            <li>@item.CreatedDate.ToString("dd/MM/yyyy")</li>
                                            <li><i class="fa-solid fa-eye"></i> @item.ViewCount</li>
                                        </ul>
                                        <p>
                                            @(item.Content.Length > 280 ? item.Content.Substring(0, 280) : item.Content) ...
                                        </p>
                                        <div class="post-options">
                                            <div class="row">
                                                <div class="col-6">
                                                    <ul class="post-tags">
                                                        <li><i class="fa fa-tags"></i></li>
                                                        <li><a href="#">@item.Category.Name</a></li>
                                                    </ul>
                                                </div>
                                                <div class="col-6">
                                                    <ul class="post-share">
                                                        <li><i class="fa fa-link"></i></li>
                                                        <li><a href="#">[Devamını Oku]</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                        <div class="col-lg-12">
                            @*<div class="main-button">
                            <a href="blog.html">View All Posts</a>
                            </div>*@

                            <ul class="pagination justify-content-center mb-4 mt-4 btn-block">

                                @if (Model.ShowPrevious)
                                {
                                    <li class="page-item">
                                        <a class="page-link" asp-route-currentPage="@(Model.CurrentPage - 1)" asp-route-pageSize="@Model.PageSize"> Önceki </a>
                                    </li>
                                }
                                @for (int i = 1; i < Model.TotalPages; i++)
                                {
                                    <li class="page-item @(i == Model.CurrentPage ? "active" : "")">

                                        <a class="page-link" asp-route-currentPage="@i" asp-route-pageSize="@Model.PageSize"> @i </a>
                                    </li>
                                }
                                @if (Model.ShowNext)
                                {
                                    <li class="page-item">
                                        <a class="page-link" asp-route-currentPage="@(Model.CurrentPage + 1)" asp-route-pageSize="@Model.PageSize"> Sonraki </a>
                                    </li>
                                }

                            </ul>

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="sidebar">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="sidebar-item search">
                                <form id="search_form" asp-controller="Home" asp-action="Search" method="GET">
                                    <input type="text" name="keyword" class="searchText" placeholder="Arama yapınız..." autocomplete="on">
                                </form>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item recent-posts">
                                <div class="sidebar-heading">
                                    <h2>Recent Posts</h2>
                                </div>
                                <div class="content">
                                    <ul>
                                        <li>
                                            <a href="post-details.html">
                                                <h5>Vestibulum id turpis porttitor sapien facilisis scelerisque</h5>
                                                <span>May 31, 2020</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="post-details.html">
                                                <h5>Suspendisse et metus nec libero ultrices varius eget in risus</h5>
                                                <span>May 28, 2020</span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="post-details.html">
                                                <h5>Swag hella echo park leggings, shaman cornhole ethical coloring</h5>
                                                <span>May 14, 2020</span>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="sidebar-item categories">
                                <div class="sidebar-heading">
                                    <h2>KATEGORİLER</h2>
                                </div>
                                @await Component.InvokeAsync("HomeCategories")
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>